<?php

namespace App;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable= ['user_id','amount','series_id'];

    protected  $dates=[
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function SerializeDate(DateTimeInterface $date)
    {
        return $date->format('d-m-Y H:i:s');
    }

    public function series()
    {
        return $this->belongsTo(Serie::class, 'series_id');
    }

    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::creating(function ($model)
        {
            $model->number = Invoice::where('series_id', $model->series_id)->max('number') +1;
        });
    }
    public function user()
    {
    	return $this->belongsTo(User::class,'user_id');
    }
}
