<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guards= [];
    protected $fillable=['p_id'];

    public function series()
    {
        return $this->belongsTo(Serie::class, 'series_id');
    }

    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::creating(function ($model)
        {
            $model->number = Order::where('series_id', $model->series_id)->max('number') +1;
        });
    }
    public function payment()
    {
        return $this->hasMany(Payment::class);
    }
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
